config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :pins

  get 'welcome/index'

  root 'welcome#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof',:as => "pinsof"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :photo, presence:true
	validates:description, presence:true

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  
  def pinsof
    @user_id = params[:user_id]
    @user= User.find(@user_id)
    @pins= @user.pins
  end

  def mypins
    @pins = current_user.pins
  end

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_used.id

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails</title>

  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>



	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.min.js">
	
	</script>
</head>

<body>
	<%= render 'shared/navbar' %>
	<p class="notice"><%= notice %></p>
	
	<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group"> 
  <div class="field">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name, :class=>'form-control', :placeholder=> "Nombre del Pin" %>
  </div>
 </div> 

<div class="form-group">
  <div class="field">
    <%= f.label :photo, "Foto" %><br>
    <%= f.text_field :photo, :class=>'form-control', :placeholder=> "URL de la imagem" %>
  </div>
</div>  
<div class="form-group"> 
  <div class="field">
    <%= f.label :description , "Descripcion"%><br>
    <%= f.text_area :description, :class=>'form-control',
      :rows=> "10", :cols => "30" %>
  </div>
 </div> 

<div class="form-group">  
  <div class="actions">
    <%= f.submit "Crear", :class => "btn btn-primary"%>
  </div>
</div>  
<% end %>

app/views/pins/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Editing pin</h1>
			<%= render 'form' %>
		</div>
	</div>
	<%= link_to 'Show', @pin %> |
	<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<h1>Descubre Pins</h1>
<div id="container">

  <% @pins.each do |pin| %>
    <div class="item" style="width:25%">
      <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img_responsive')  %>
        <%= pin.description %>
        <div :class="buttons" style="margin-top:10px; margin-bottom:10px">
          <%= link_to 'Show', pin, :class=> 'btn' %>
          <%= link_to 'Edit', edit_pin_path(pin),:class=> 'btn' %>
          <% if user_signed_in? %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' },:class=> 'btn' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

<br>
  <% if user_signed_in? %>
    <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>

<script type="text/javascript">
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
$(window).load(function(){
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
})
</script>

app/views/pins/mypins.html.erb
<h1>Mis Pins</h1>
<div id="container">
  <% @pins.each do |pin| %>
    <div class="item" style="width:25%">
      <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img_responsive')  %>
        <%= pin.description %>
        <div :class="buttons" style="margin-top:10px; margin-bottom:10px">
          <%= link_to 'Show', pin, :class=> 'btn' %>
          <%= link_to 'Edit', edit_pin_path(pin),:class=> 'btn' %>
          <% if user_signed_in? %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' },:class=> 'btn' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

<br>
  <% if user_signed_in? %>
    <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>

<script type="text/javascript">
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
$(window).load(function(){
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
})
</script>

<br>
  <% if user_signed_in? %>
    <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
	<h1>Agregar nuevo pin</h1>
	<div class="row">X
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
	<p> <%= link_to 'Back', pins_path %></p>

</div>

app/views/pins/pinsof.html.erb
<div class="container">
  <h1>Mas Pins</h1>


  <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img_responsive')  %>
        <%= pin.description %>
        <div :class="buttons" style="margin-top:10px; margin-bottom:10px">
          <%= link_to 'Show', pin, :class=> 'btn' %>
          <%= link_to 'Edit', edit_pin_path(pin),:class=> 'btn' %>
          <% if user_signed_in? %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' },:class=> 'btn' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>


app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= image_tag(@pin.name ) %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style=> 'width:500px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description%>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

<%= link_to 'Mas pins del mismo usuario', pinsof_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom:0px">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path%>">Mi pinterest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Nosotros <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= mypins_path %>">Mis Pins</a></li>
        <li><a href="<%= pins_path %>">Pins</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
          <li><a href="<%= new_user_session_path%>">Ingreso</a></li>
          <li><a href="<%= new_user_registration_path%>">Registro</a></li>
        <% else %>
          <li><a href="<%= destroy_user_session_path%>" data-method="DELETE">Salir</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<div class="container" >
			
			<h1 class="titulos" style="color:darkwhite" >Mi Pinterest <br> <small style="font-size:25px">“Hay una fuerza motriz más poderosa que el vapor, la electricidad y la energía atómica: la voluntad.” .- Albert Einstein </small> </h1>
			<a href="http://resuelvetudeuda.com/" target="_blank" class="btn btn-default"> 
			Learn more
			<SPAN class="glyphicon glyphicon-pencil " style="font-size 20px; color:darkorange"> </SPAN>
			</a>  
	</div>	
</div>

<div class="container">
	
	<div class="row">
		<div class="col-md-4">
			<div class="page-header">
		  		<h2 style="display:inline; color:slategray">¿Quienes somos? </h2>
		  		<span class="label label-default">New</span></h3>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<a href="http://google.com" target="_blank"> Conoce mas de nosotros</a>
			<br>
			<br>

			<img id="img2" src="http://fotos-lindas.com/wp-content/uploads/2015/07/Fotos-del-atardecer.jpg" class="img-responsive" height="100px"/>
		</div>

		<div class="col-md-4">
			<div class="page-header">
			<h2 style=" color:slategray">¿Como formar parte?</h2>		
			</div>
			<p class="titulos">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<ol>
				<li>Mexico</li>
				<li>Bogota</li>
				<li>Brasil</li>
			</ol>
		</div>
		<div class="col-md-4">
			<div class="page-header">
				<h2 style=" color:slategray">No te arrepentiras!!! </h2>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

			<h6>Sub ... Subtítulo </h6>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

			<a href="http://google.com">
				<img src="http://axxon.com.ar/noticias/imagenes/2012/0126-PIA15258_ip.jpg"
				alt="logo sistema" class="img-responsive ">
			</a>
			
		</div>
	</div>
</div>